### PR TITLE
v1 styling/branding updates

### PR DESCRIPTION
**Pull request by blainehussey**
PR to close issues #7 and #2, basic styling of tiles, along with footer and header.

### CODE REVIEW

**Comment by blainehussey** [comment]
https://deploy-preview-13--focused-beaver-3cc79d.netlify.com

**Review by Mrc0113 — APPROVED** [review]
Looks good! 
@jerdog - if all looks good to you go ahead and merge!

**Comment by jerdog** [comment]
This is great, and looks awesome on mobile as well

**Review by jerdog — APPROVED** [review]
Approved - looks great

**Pull request merged**
